---
title: "R Notebook"
output: html_notebook
---

## Course Schedule
*(subject to change in order to best meet your learning needs and interests)*

Session|Topic|Readings + Other Preparation|Assignments Due
---------|------------|------------------------------------|--------------
Wk 1 Jan 26	| Introduction to Learning Analytics & Educational Data Science	|	Educause (2015). [Why is measuring learning so difficult?](http://er.educause.edu/multimedia/2015/8/why-is-measuring-learning-so-difficult-v) |
Wk 2 Feb 2 | State of the Field:</br>Origins & Key Issues | Siemens, G. (2013). [Learning analytics: The emergence of a discipline](http://journals.sagepub.com/doi/pdf/10.1177/0002764213498851). *American Behavioral Scientist, 57*(10), 1380-1400. </br> </br> Ferguson, R., et al. (2016). [Research evidence on the use of learning analytics: Implications for education policy](http://publications.jrc.ec.europa.eu/repository/bitstream/JRC104031/lfna28294enn.pdf). Publications Office of the European Union: JRC Science for Policy Report. </br> **(p8-27 only)** | [Software &  Tool Set-Up](https://github.com/learninganalytics-datascience-edu/syllabus/blob/master/SoftwareAndTools.Rmd) </br> </br>  [#wk2discuss](https://ladsedu.slack.com/messages/wk2discuss/) </br> </br> Bring ideas of learning-related things we could measure / track about ourselves 
Wk 3 Feb 9 | | Snow Day | |
Wk 4 Feb 16 | Diving Into Data</br>(and Cleaning It Up) | Selwyn, N. (2015). [Data entry: Towards the critical study of digital data and education](http://www.tandfonline.com/doi/abs/10.1080/17439884.2014.921628?journalCode=cjem20). *Learning, Media and Technology, 40*(1), 64-82. **(NYU Login Req)**</br> </br> Wise, A. F., & Schaffer, D. W. (2015). [Why theory matters more than ever in the age of big data](http://epress.lib.uts.edu.au/journals/index.php/JLA/article/view/4677). *Journal of Learning Analytics, 2*(2), 5–13.| [R Swirl Tutorial](https://github.com/learninganalytics-datascience-edu/R-Swirl-Tutorials) </br> </br> [#wk3discuss](https://ladsedu.slack.com/messages/wk3discuss/)
Wk 5 Feb 23 | Finding Meaningful Groupings with Clustering	| Wise, A. F., Speer, J., Marbouti, F., & Hsiao, Y. T. (2013). [Broadening the notion of participation in online discussions: examining patterns in learners’ online listening behaviors](http://link.springer.com/article/10.1007/s11251-012-9230-9). *Instructional Science, 41*(2), 323-343. **(NYU Login Req)** | [Individual Data Assignment #1 (Data Wrangling)](https://github.com/learninganalytics-datascience-edu/IndividualAssignment1) </br> </br> [#wk5discuss](https://ladsedu.slack.com/messages/wk5discuss/)
Wk 6 Mar 2   |  Machine Learning Overview	| [A Visual Introduction to Machine Learning](http://www.r2d3.us/visual-intro-to-machine-learning-part-1/) (Prediction via Decision Trees)  </br> </br> Zheng, A. (2015). [Evaluating machine learning models](http://www.oreilly.com/data/free/evaluating-machine-learning-models.csp?intcmp=il-data-free-lp-lgen_free_reports_page). O’Reily Media. (Chps. 1-3 / pp 1-26 ).	| [#wk6discuss](https://ladsedu.slack.com/messages/wk6discuss/)  </br> </br> Enter online [SNA](https://docs.google.com/spreadsheets/d/1YtAPnHDXyGHAouiqTW2tzA9x9D9c89JzFQPb1MLmQOI/edit#gid=800113348) and [Reading](https://docs.google.com/a/nyu.edu/forms/d/e/1FAIpQLSe0QkrMiotLFT7PvrSDMCx8007WWYvDTX5rfynt2kff0I5YMg/viewform?c=0&w=1) data
Wk 7 Mar 9  |  Predictive Modelling |*Two short (5pp) papers from LAK16* **(NYU Login Req)** </br> </br>Rienties, B., & Toetenel, L. (2016). [The impact of 151 learning designs on student satisfaction and performance: Social learning (analytics) matters](http://dl.acm.org/citation.cfm?id=2883875&CFID=906638631&CFTOKEN=42327609). In Proceedings of LAK'16 (pp. 339-343). ACM. </br> </br> Pardo, A., et al. (2016). [Generating actionable predictive models of academic performance](http://dl.acm.org/citation.cfm?id=2883870&CFID=906638631&CFTOKEN=42327609). In Proceedings ofLAK'16 (pp. 474-478). ACM. |  Individual Data Assignment #2 (Clustering) </br> </br> [#wk7discuss](https://ladsedu.slack.com/messages/wk7discuss/)   </br> </br> Enter online [SNA](https://docs.google.com/spreadsheets/d/1YtAPnHDXyGHAouiqTW2tzA9x9D9c89JzFQPb1MLmQOI/edit#gid=800113348) and [Reading](https://docs.google.com/a/nyu.edu/forms/d/e/1FAIpQLSe0QkrMiotLFT7PvrSDMCx8007WWYvDTX5rfynt2kff0I5YMg/viewform?c=0&w=1) data
Wk 8 Mar 16  | | No Class (Spring Break) | 
Wk 9 Mar 23 | Social Network Analysis I |	Grunspan et al. (2014). [Understanding classrooms through social network analysis: A primer for social network analysis in education research](http://www.lifescied.org/content/13/2/167.full). CBE-Life Sciences Education, 13(2), 167–178.|	Individual Data Assignment #3 (Predictive Modelling) </br> </br> #wk9discuss |
Wk 10 Mar 30  | Social Network Analysis II | Wise, Cui & Jin (in final preparation) [Finding Community in the Crowd: The Importance of Tie Definition and Networking Partitioning in Examining Social Learning in MOOCs](https://github.com/learninganalytics-datascience-edu/syllabus/blob/master/MOOC%20SNA%20Paper%20-%20Wise%20Et%20Al.pdf) | #wk10discuss
Wk 11 Apr 6   | Natural Language Processing  | McNamara et al. (2017) [Natural Language Processing and Learning Analytics](https://github.com/learninganalytics-datascience-edu/syllabus/blob/master/McNamaraEtAl2017-NLP%2BLearningAnalytics.pdf) Chptr. 8 in the forthcoming Handbook of Learning Analytics</br></br> Rose, C. P. (2017) [Discourse Analytics](https://github.com/learninganalytics-datascience-edu/syllabus/blob/master/Rose2017-DiscourseAnalytics.pdf) Chptr. 9 in the forthcoming Handbook of Learning Analytics| Individual Data Assignment #4 (Social Network Analysis) due Friday </br> </br> 
Wk 12 Apr 13 | Visualization & Dashboards | Klerxk, Verbert & Duval (2017) [Learning analytics dashboards](https://github.com/learninganalytics-datascience-edu/syllabus/blob/master/KlekxVerbertDuval-LearningAnalyticsDashboards.pdf) Chptr 12 in the forthcoming Handbook of Learning Analytics. </br> </br> Duval, E. (2011). [Attention please!: Learning analytics for visualization and recommendation.](https://lirias.kuleuven.be/bitstream/123456789/315113/1/)  Proceedings of LAK'11 (pp. 9-17). ACM. | 
Wk 13 Apr 20 |  Implementation & Use of Learning Analytics	| Wise, A., Zhao, Y., & Hausknecht, S. (2014). [Learning analytics for online discussions: Embedded and extracted approaches](http://epress.lib.uts.edu.au/journals/index.php/JLA/article/view/3532/4157). Journal of Learning Analytics, 1(2), 48-71. </br> </br>	Lee, V. R., & Drake, J. (2013). [Quantified recess: Design of an activity for elementary students involving analyses of their own movement data](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.842.5&rep=rep1&type=pdf). In IDC'13 (pp. 273-276). ACM. **(NYU Login Req)** | 
Wk 14 Apr 27 | Ethics & Privacy Issues | Young, J.R. (2014). Why students should own their educational data. *The Chronicle of Higher Education Blogs: Wired Campus*. </br></br> Slade, S. & Prinsloo, P. (2013). Learning analytics: ethical issues and dilemmas. *American Behavioral Scientist, 57*(10),1509–1528. |
Wk 15 May 4 | Wrapping Up | Final class – no readings | Group Project

