---
title: "Syllabus"
output: html_notebook
---

## Learning Analytics & Data Science in Education (EDCT GE-2252)

---

### Spring 2018 | Th 4:55-6:35 | MAGNET 805 | Dr. Alyssa Wise | alyssa.wise@nyu.edu 

### Overview

Advances in computing, internet, and sensing technologies are changing our relationship to data in all areas of life, including education and learning. Large quantities of detailed information is now routinely collected as part of our interaction with digital learning tools and social media, and tools for data collection in physical spaces are rapidly becoming more affordable and less intrusive. This creates exciting opportunities to generate insight that can help us better understand and improve learning, but it also raises questions about data rights, validity issues for different data-based inferences, and more broadly concerns about what the utilization of this data may mean for education and society. Importantly, the increasing prevalence and pervasiveness of data means that in the near future, critically assessing and making informed decisions about data use will be part of every education-related career.

Learning Analytics & Data Science in Education provides an introduction to uses of data in education that will help students develop their ability to evaluate data sources, perform analyses and critically evaluate applications of data use in real world educational situations. The course weaves together three strands of focus: a conceptual concern with selecting and interpreting data-based information, a technical emphasis on working with data and performing analyses, and a societal lens on understanding the opportunities, challenges and concerns that such data use presents. There are no pre-requisites for this course and no previous experience in statistics, computer science or data manipulation is expected; however, students will be introduced to and asked to work with a selected set of data analysis tools and techniques during the course.

Specific topics covered will include a subset of: data types and sources, data cleaning and organization methods, exploration and visualization approaches, network analysis, structure discovery, classification techniques, text mining, prediction modeling, dashboards, analytic sense-making, data-informed decision-taking, analytics implementation design, institutional factors, data ethics and policy issues.

### Course Goals
The overarching goal of this course is for students to acquire the knowledge and skills to be intelligent producers and consumers of learning analytics and data science in education. By the end of the course students will be able to:

  + Systematically select, analyze and interpret data to make an argument about learning
  + Take an informed position on research, policy, and practice issues related to educational data science

This necessarily means that students become comfortable with the educational applications of three domain areas: computer science, statistics, and data-informed decision-making. There is no expectation for students to become experts in any single area. Rather the course will enhance student competency in identifying and reasoning through issues at the level of data acquisition, analysis and application in education.

### Course Requirements
Assignment|Description|Weight
----------|----------------------------|------
Online and In-Class Engagement (ongoing)	| This includes active and prepared participation during in-class sessions, in online exchanges about the readings, and as part of the class community in asking and answering questions about data, analysis and interpretation. |	20%
Individual Data Science Assignments (4) |	Using provided tools and/or code, conduct and interpret the results of various data processing and analyses approaches (e.g. data cleaning, dimension reduction, clustering, predictive modelling, social network analysis, natural language processing). |	50%
Group Data Science Project (1)	| Design, conduct and interpret an analysis designed to produce a particular kind of insight into specific data. |	30%

### Online Space & Communication
We will have two online spaces for this course. The first is in [GitHub](https://github.com/learninganalytics-datascience-edu), an online version control system repository. This is where I will upload all course documents and resources. It is also where I will post and you will submit assignments. You will need to create a (free) GitHub account and then I will add you to our class organization so you will have access to all the files. 

The second space is in [Slack](https://ladsedu.slack.com/) an online team collaboration tool. This will be the hub for our communication and the go-to place for discussing the readings and connecting with classmates when you have technical problems. Finally, you should also make sure that you have a working NYU email account (which you check regularly).

+ **Github Course Space:** <https://github.com/learninganalytics-datascience-edu>
+ **Slack Course Space:** <https://ladsedu.slack.com>

### Readings
Course readings come from a variety of scholarly journals and edited book volumes. The majority of these are available online through the [NYU Library](https://library.nyu.edu/) and you are welcome to work with them in digital or print form as you wish. Exceptions are noted on the week-by-week schedule with a link or digital file provided.

Each week that readings are assigned, you are expected to discuss the key ideas and/or questions raised in our [Slack Course Space](https://ladsedu.slack.com/). You should make at least two high quality comments each week (these may relate to any combination of the week's readings). High quality comments are ones which are: 

  + *Thoughtful* about the readings
  + *Rationaled* in backing up ideas with evidence/theory
  + *Connected* to what has been said already.

### Software
You will be asked to download, install and use a number of data analysis and generation tools as part of your work in this course. All required tools are freely available on the web and are supported by communities of users which generate documentation, offer tutorials, and ask and answer questions to help each other. The primary tools you we will be working with this term are R and R Studio. Detailed information about how to install and set these up for the class is provided on the [Software &  Tool Set-Up](https://github.com/learninganalytics-datascience-edu/syllabus/blob/master/SoftwareAndTools.Rmd) page.

### Accessibility
Any student attending NYU who needs an accommodation due to a chronic, psychological, visual, mobility and/or learning disability, or is Deaf or Hard of Hearing should register with the Moses Center for Students with Disabilities, 719 Broadway, 2nd Floor, 212.998.4980 (telephone and TTY), <http://www.nyu.edu/csd>.

### Digital Devices in Class
Technology has become an integral tool to our working, scholarly and personal lives. It can also be a very tempting distraction… As our course is intimately connected to the use of technology in education, and we will be doing a variety of hands-on exercises, you are expected to bring a laptop with you to class. However, it important to make sure that you are using your digital device to support, rather than detract from, your presence in class. Beyond the specific data mining exercises will we do as a group, looking up relevant information on-the-spot and taking notes (perhaps real-time collaboratively or to share digitally with your classmates) are ways a laptop can support classroom learning. Please refrain from checking social media or surfing the web during class – your classmates can tell if you are being disrespectful by only half-listening to their ideas.

### Course Scheduling
**Attendance:** Because this is a seminar course, class meetings, discussions and activities are central to the learning process and your attendance at all class sessions is expected. Students should notify instructors at the beginning of the semester about their wishes to observe holidays on days when class sessions are scheduled. Where academic scheduling conflicts prove unavoidable, no student will be penalized for absence due to religious reasons, and alternative means will be sought for satisfying the academic requirements involved. If you have to miss a class for other reasons, please let me know beforehand so we can make alternate arrangements for you to keep up with the material. Multiple unexcused absences and/or failure to make up missed class work will negatively impact your grade. 

**Assignments:** Due dates for all assignments have been provided and need to be respected. I realize that you all have many other demands on your time, so please plan ahead. If you have a special circumstance or scheduling conflict you wish to discuss, please talk with me as soon as possible. Unless you have negotiated with me ahead of time, course policy is that late work will only be accepted within one week of the due date and the mark will be reduced by one letter grade increment. 

**Incompletes:** The grade of Incomplete will be assigned only when the course attendance requirement has been met but, for reasons satisfactory to the instructor, the granting of a final grade has been postponed because certain course assignments are outstanding. Outstanding assignments must be completed within the agreed upon time frame to be included in the final grade. Otherwise, the grade will either remain as a permanent Incomplete, be changed to the grade earned without the outstanding assignments, or default to a non-passing grade, as determined by School and/or University Policy. For more information, students should speak with their advisors or program directors.

### Grading 
Grade |Descriptor
-------|--------------------------------------
A | *Excellent.*	Work is sophisticated, creative, thorough, well-reasoned, and appropriately applies relevant course concepts. Exceptional accomplishment of course objectives.
A- | *Very Good.*	Work is thorough, well-reasoned, and appropriately applies relevant course concepts. Strong accomplishment of course objectives.
B+ | *Good.* Work is mostly well-reasoned and appropriately applies some relevant course concepts. Satisfactory accomplishment of course objectives.
B | *Adequate.* Work shows some appropriate application of relevant course concepts but others elements are missing, weakly applied or used inappropriately. Basic accomplishment of course objectives.
B- | *Borderline.*	Work shows uneven application of course concepts with core elements missing, weakly applied or used inappropriately. Marginal accomplishment of course objectives. 
C+ to D| *Deficient.* Work is inadequate. It is poorly developed or flawed by multiple missing, weak or inappropriately applied elements. Minimal accomplishment of course objectives.  
F | *Fail.*	Work fails to meet minimal expectations for course credit for graduate work.  Accomplishment is consistently weak, with serious limitations in many areas.  

### Academic Integrity
Academic integrity is the guiding principle for all that you do at the university; from taking exams, to writing code and from reporting data analyses to writing term papers. It requires that you recognize and acknowledge data, information and algorithms derived from others, and take credit only for ideas and work that are yours. You violate the principle of academic integrity when you submit work created by someone else, submit the same work for two different courses without prior permission, fail to acknowledge help you receive completing course assignments or plagiarize.

It is expected that all work turned in for this course will be your own original work with appropriate credit given to all sources used. This holds for both written compositions and code. There are many open source resources available to help you in your work in this course. You are encouraged to both use and appropriately acknowledge these sources. Students who submit work that is either not their own or without clear attribution to the original source, fabricate data or engage in cheating / misrepresentation may be penalized for academic dishonesty.  

### Resources
  +	[Steinhardt’s Academic Integrity Policy](http://steinhardt.nyu.edu/policies/academic_integrity)
  + [NYU’s Academic Integrity Policy](http://www.nyu.edu/about/policies-guidelines-compliance/policies-and-guidelines/academic-integrity-for-students-at-nyu.html)
  +	[APA Style Guide](http://guides.nyu.edu/apa)

### Expectations
You will…

+ do the readings and complete the assignments consistently
+ actively contribute to class activities online and in-person
+ ask for help or support from your peers and myself when you need it
+ be an active and collaborative technical problem-solver (*give that help back!*)
+ pick a project that is interesting and meaningful to you
+ have fun exploring ideas and data in this course!


